### PR TITLE
[R] If mergebox is not disabled, avoid another fiber

### LINKED ISSUE #6: [Question] Why run in a fiber ?
https://github.com/peerlibrary/meteor-control-mergebox/blob/master/server.coffee#L65

Why do you run this in a separate fiber ?

I also looked here, but don't fully understand:
https://github.com/peerlibrary/node-fiber-utils/blob/master/src/server.coffee#L49

### PR DESCRIPTION
**Pull request by theodorDiaconu**
Fixes #6

Also, why do you even need another fiber, can't it be removed completely ?

### CODE REVIEW

**Comment by mitar** [comment]
I do not think this is a good fix.

Can you make a small reproduction (ideally a PR with a test case against this repo) with what is happening to you?

**Comment by theodorDiaconu** [comment]
@mitar the first issue is that it changes the original behavior of "added" even if you don't do this.disableMergebox()

**Comment by mitar** [comment]
Oh, you are right. I was misreading the code. Who made such ugly code `unless disabled` where `disabled` is enabling disabling of merge box. So hard to read. :-)

Can you move return even before the ID string manipulation? That is also not necessary if mergebox is not disabled?

And thanks!

This was really more of proof of an idea package.

**Comment by convexset** [comment]
*PING*

Also pointing @mitar to https://github.com/peerlibrary/meteor-control-mergebox/issues/10

**Pull request merged**
